-- AlterTable
ALTER TABLE "LayoutGroup" ADD COLUMN     "posX" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "posY" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "posZ" DOUBLE PRECISION NOT NULL DEFAULT 0;
