-- AlterTable
ALTER TABLE "QuoteItem" ADD COLUMN     "assemblyType" TEXT NOT NULL DEFAULT 'LATERAL_PASANTE',
ADD COLUMN     "backThicknessMM" DOUBLE PRECISION NOT NULL DEFAULT 15,
ADD COLUMN     "thicknessMM" DOUBLE PRECISION NOT NULL DEFAULT 18,
ADD COLUMN     "zocalo" DOUBLE PRECISION NOT NULL DEFAULT 8;
